services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ketu_frontend
    ports:
      - "${FRONTEND_PORT:-4000}:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:18080}
      BOT_TOKEN: ${BOT_TOKEN}
    restart: unless-stopped
